- id: docker-image
  name: Docker image
  description: Run Docker image with extended DinD detection.
  entry: docker-image
  language: python

- id: check-helm-version
  name: Helm version
  description: Check whether the Helm chart version was incremented.
  entry: check-helm-version
  language: python
