repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        name: Markdownlint

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        name: Python black code formatter
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Python flake8

  - repo: local
    hooks:
      - id: python_unittest
        name: Python unittest
        language: python
        entry: python -m unittest discover -s tests -p '*.py'
        types:
          - python
        additional_dependencies:
          - pre-commit
          - GitPython>=3.1.32
          - semver>=2.13.0
          - ruamel.yaml>=0.17.32
        pass_filenames: false
