- id: docker-image
  name: Docker image
  description: Run Docker image with extended DinD detection.
  entry: docker-image
  language: python

- id: check-helm-version
  name: Helm version
  description: Check whether the Helm chart version was incremented.
  entry: check-helm-version
  language: python
  files: ^(helper-|)charts/[^/]+/(\.kubeconform|\.helmignore|templates/NOTES.txt|.*\.(ya?ml|json|tpl))$
  require_serial: true

- id: check-version
  name: Version
  description: Check whether the version file was incremented.
  entry: check-version
  language: python
  files: ^.*$
  require_serial: true
